[build]
  command = "ng build --configuration=production && ng run sikkim-newar-guthi:server:production"
  publish = "dist/sikkim-newar-guthi/browser"

[[plugins]]
  package = "@netlify/angular-runtime"
